-- Migration: Create agent analysis tables
-- Date: 2026-04-03
-- Description: Tables for multi-agent analysis framework

-- trading_analysis
CREATE TABLE IF NOT EXISTS trading_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_id BIGINT NOT NULL REFERENCES parsed_research(id),
    agent_type TEXT NOT NULL DEFAULT 'trading_opportunities',
    opportunities JSONB NOT NULL DEFAULT '[]',
    no_opportunity_reason TEXT,
    analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(research_id, agent_type)
);

CREATE INDEX IF NOT EXISTS idx_trading_analysis_research_id ON trading_analysis(research_id);
CREATE INDEX IF NOT EXISTS idx_trading_analysis_analyzed_at ON trading_analysis(analyzed_at);

-- short_time_horizon_analysis  
CREATE TABLE IF NOT EXISTS short_time_horizon_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_id BIGINT NOT NULL REFERENCES parsed_research(id),
    agent_type TEXT NOT NULL DEFAULT 'short_time_horizon',
    insights JSONB NOT NULL DEFAULT '[]',
    summary TEXT,
    analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(research_id, agent_type)
);

CREATE INDEX IF NOT EXISTS idx_short_time_horizon_research_id ON short_time_horizon_analysis(research_id);
CREATE INDEX IF NOT EXISTS idx_short_time_horizon_analyzed_at ON short_time_horizon_analysis(analyzed_at);

-- talking_points_analysis
CREATE TABLE IF NOT EXISTS talking_points_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_id BIGINT NOT NULL REFERENCES parsed_research(id),
    agent_type TEXT NOT NULL DEFAULT 'talking_points',
    talking_points JSONB NOT NULL DEFAULT '[]',
    primary_headline TEXT,
    analyzed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(research_id, agent_type)
);

CREATE INDEX IF NOT EXISTS idx_talking_points_research_id ON talking_points_analysis(research_id);
CREATE INDEX IF NOT EXISTS idx_talking_points_analyzed_at ON talking_points_analysis(analyzed_at);
